##### The Odds API Setup
- 500 request limit on Free tier
- Important note: the lines are delayed by several minutes, meaning I may need another scraping tool

In [8]:
import requests
from pandas import json_normalize

API_KEY = "fc35e20b0a8d983f77fc2fa9257a35c7"
SPORTS_URL = f"https://api.the-odds-api.com/v4/sports?apiKey={API_KEY}"
# ODDS_URL = f"https://api.the-odds-api.com/v4/sports/baseball_mlb_preseason/odds/?apiKey={API_KEY}&regions=us&markets=h2h,spreads,totals,outrights&oddsFormat=american"
ODDS_URL = f"https://api.the-odds-api.com/v4/sports/baseball_mlb/odds/?apiKey={API_KEY}&regions=us&markets=outrights&oddsFormat=american"


response = requests.get(SPORTS_URL)
sportsbook_data = response.json()
sports = json_normalize(sportsbook_data)
sports[sports["has_outrights"] == False]

,key,group,title,description,active,has_outrights
0,americanfootball_cfl,American Football,CFL,Canadian Football League,True,False
1,americanfootball_ncaaf,American Football,NCAAF,US College Football,True,False
3,americanfootball_nfl,American Football,NFL,US Football,True,False
4,americanfootball_nfl_preseason,American Football,NFL Preseason,US Football,True,False
6,aussierules_afl,Aussie Rules,AFL,Aussie Football,True,False
7,baseball_kbo,Baseball,KBO,KBO League,True,False
8,baseball_mlb,Baseball,MLB,Major League Baseball,True,False
10,baseball_npb,Baseball,NPB,Nippon Professional Baseball,True,False
13,basketball_wnba,Basketball,WNBA,US Basketball,True,False
14,boxing_boxing,Boxing,Boxing,Boxing Bouts,True,False
15,cricket_t20_blast,Cricket,T20 Blast,T20 Blast,True,False
16,cricket_test_match,Cricket,Test Matches,International Test Matches,True,False
17,cricket_the_hundred,Cricket,The Hundred,The Hundred,True,False
21,icehockey_nhl,Ice Hockey,NHL,US Ice Hockey,True,False
23,icehockey_sweden_hockey_league,Ice Hockey,SHL,Swedish Hockey League,True,False
24,lacrosse_pll,Lacrosse,PLL,Premier Lacrosse League,True,False
25,mma_mixed_martial_arts,Mixed Martial Arts,MMA,Mixed Martial Arts,True,False
27,rugbyleague_nrl,Rugby League,NRL,Aussie Rugby League,True,False
28,soccer_argentina_primera_division,Soccer,Primera División - Argentina,Argentine Primera División,True,False
29,soccer_austria_bundesliga,Soccer,Austrian Football Bundesliga,Austrian Soccer,True,False
30,soccer_belgium_first_div,Soccer,Belgium First Div,Belgian First Division A,True,False
31,soccer_brazil_campeonato,Soccer,Brazil Série A,Brasileirão Série A,True,False
32,soccer_brazil_serie_b,Soccer,Brazil Série B,Campeonato Brasileiro Série B,True,False
33,soccer_chile_campeonato,Soccer,Primera División - Chile,Campeonato Chileno,True,False
34,soccer_china_superleague,Soccer,Super League - China,Chinese Soccer,True,False
35,soccer_conmebol_copa_libertadores,Soccer,Copa Libertadores,CONMEBOL Copa Libertadores,True,False
36,soccer_denmark_superliga,Soccer,Denmark Superliga,Danish Soccer,True,False
37,soccer_efl_champ,Soccer,Championship,EFL Championship,True,False
38,soccer_england_efl_cup,Soccer,EFL Cup,League Cup,True,False
39,soccer_england_league1,Soccer,League 1,EFL League 1,True,False
40,soccer_england_league2,Soccer,League 2,EFL League 2,True,False
41,soccer_epl,Soccer,EPL,English Premier League,True,False
43,soccer_finland_veikkausliiga,Soccer,Veikkausliiga - Finland,Finnish Soccer,True,False
44,soccer_france_ligue_one,Soccer,Ligue 1 - France,French Soccer,True,False
45,soccer_france_ligue_two,Soccer,Ligue 2 - France,French Soccer,True,False
46,soccer_germany_bundesliga,Soccer,Bundesliga - Germany,German Soccer,True,False
47,soccer_germany_bundesliga2,Soccer,Bundesliga 2 - Germany,German Soccer,True,False
48,soccer_germany_liga3,Soccer,3. Liga - Germany,German Soccer,True,False
49,soccer_italy_serie_a,Soccer,Serie A - Italy,Italian Soccer,True,False
50,soccer_japan_j_league,Soccer,J League,Japan Soccer League,True,False
51,soccer_korea_kleague1,Soccer,K League 1,Korean Soccer,True,False
52,soccer_mexico_ligamx,Soccer,Liga MX,Mexican Soccer,True,False
53,soccer_netherlands_eredivisie,Soccer,Dutch Eredivisie,Dutch Soccer,True,False
54,soccer_norway_eliteserien,Soccer,Eliteserien - Norway,Norwegian Soccer,True,False
55,soccer_poland_ekstraklasa,Soccer,Ekstraklasa - Poland,Polish Soccer,True,False
56,soccer_portugal_primeira_liga,Soccer,Primeira Liga - Portugal,Portugese Soccer,True,False
57,soccer_spain_la_liga,Soccer,La Liga - Spain,Spanish Soccer,True,False
58,soccer_spain_segunda_division,Soccer,La Liga 2 - Spain,Spanish Soccer,True,False
59,soccer_spl,Soccer,Premiership - Scotland,Scottish Premiership,True,False
60,soccer_sweden_allsvenskan,Soccer,Allsvenskan - Sweden,Swedish Soccer,True,False
61,soccer_sweden_superettan,Soccer,Superettan - Sweden,Swedish Soccer,True,False
62,soccer_switzerland_superleague,Soccer,Swiss Superleague,Swiss Soccer,True,False
63,soccer_uefa_champs_league_qualification,Soccer,UEFA Champions League Qualification,European Champions League Qualification,True,False
64,soccer_usa_mls,Soccer,MLS,Major League Soccer,True,False

In [5]:
sports

,message,error_code,details_url
0,Invalid parameter combination. The given marke...,INVALID_MARKET_COMBO,https://the-odds-api.com/liveapi/guides/v4/api...

#### Testing theoddsapihelper.py

In [1]:
from theoddsapihelper import TheOddsAPIHelper

oddsapi = TheOddsAPIHelper()
full_odds = oddsapi.get_odds_table()
# full_odds.to_csv("test_selected_sports_results.csv")

# print(oddsapi.requests_made)

In [2]:
full_odds.shape

(84, 14)

#### Initial Data Ingestion
- Will code most of this in pandas but I need to see if a spark/polars dataframe would work better
long term

In [50]:
import pandas as pd

sportsbook = pd.DataFrame(sportsbook_data)

In [18]:
import polars as pl

pl_sportsbook = pl.DataFrame(sportsbook_data)

In [19]:
# Sample pyspark code

from pyspark.sql import SparkSession
from pyspark.sql.types import StructType, StructField, IntegerType, StringType

# Create a Spark session
spark = SparkSession.builder.appName("example").getOrCreate()

# JSON data
api_response = [
    {"id": 1, "name": "Alice", "age": 25},
    {"id": 2, "name": "Bob", "age": 30},
    {"id": 3, "name": "Charlie", "age": 22},
]

# Define the schema for the DataFrame
schema = StructType([
    StructField("id", IntegerType(), True),
    StructField("name", StringType(), True),
    StructField("age", IntegerType(), True),
])

# Create a PySpark DataFrame
df = spark.createDataFrame(api_response, schema=schema)

# Show the DataFrame
df.show()

+---+-------+---+
| id|   name|age|
+---+-------+---+
|  1|  Alice| 25|
|  2|    Bob| 30|
|  3|Charlie| 22|
+---+-------+---+

#### Preview sample dataset, top 40 results for NBA

In [3]:
full_odds.sample(10)

,outcomes_name,outcomes_price,outcomes_point,id,markets_key,markets_last_update,bookmakers_key,bookmakers_title,bookmakers_last_update,sport_key,sport_title,commence_time,home_team,away_team
13,Under,-120,7.5,e609747ab2ded965a1db3a6f03d0eb31,totals,2024-07-16T16:03:17Z,betmgm,BetMGM,2024-07-16T16:03:17Z,baseball_mlb,MLB,2024-07-17T00:11:00Z,American League,National League
37,Under,-120,7.5,e609747ab2ded965a1db3a6f03d0eb31,totals,2024-07-16T16:03:17Z,draftkings,DraftKings,2024-07-16T16:03:17Z,baseball_mlb,MLB,2024-07-17T00:11:00Z,American League,National League
25,National League,100,NaN,e609747ab2ded965a1db3a6f03d0eb31,h2h,2024-07-16T16:03:17Z,draftkings,DraftKings,2024-07-16T16:03:17Z,baseball_mlb,MLB,2024-07-17T00:11:00Z,American League,National League
17,Under,-120,7.5,e609747ab2ded965a1db3a6f03d0eb31,totals,2024-07-16T16:03:17Z,betmgm,BetMGM,2024-07-16T16:03:17Z,baseball_mlb,MLB,2024-07-17T00:11:00Z,American League,National League
43,National League,100,NaN,e609747ab2ded965a1db3a6f03d0eb31,h2h,2024-07-16T16:03:18Z,fanduel,FanDuel,2024-07-16T16:03:18Z,baseball_mlb,MLB,2024-07-17T00:11:00Z,American League,National League
56,American League,-120,NaN,e609747ab2ded965a1db3a6f03d0eb31,h2h,2024-07-16T16:03:17Z,superbook,SuperBook,2024-07-16T16:03:17Z,baseball_mlb,MLB,2024-07-17T00:11:00Z,American League,National League
14,Over,100,7.5,e609747ab2ded965a1db3a6f03d0eb31,totals,2024-07-16T16:03:17Z,betmgm,BetMGM,2024-07-16T16:03:17Z,baseball_mlb,MLB,2024-07-17T00:11:00Z,American League,National League
33,National League,165,-1.5,e609747ab2ded965a1db3a6f03d0eb31,spreads,2024-07-16T16:03:17Z,draftkings,DraftKings,2024-07-16T16:03:17Z,baseball_mlb,MLB,2024-07-17T00:11:00Z,American League,National League
81,Under,-118,7.5,e609747ab2ded965a1db3a6f03d0eb31,totals,2024-07-16T16:03:18Z,williamhill_us,Caesars,2024-07-16T16:03:18Z,baseball_mlb,MLB,2024-07-17T00:11:00Z,American League,National League
11,National League,-205,1.5,e609747ab2ded965a1db3a6f03d0eb31,spreads,2024-07-16T16:03:17Z,betmgm,BetMGM,2024-07-16T16:03:17Z,baseball_mlb,MLB,2024-07-17T00:11:00Z,American League,National League